### ISSUE TITLE
Naming links for report file

### ISSUE THREAD

**Issue by hma211** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group4#15]
Hi guys, I'm trying to put in links to our test function and run test files for the report file. The links are super long and thus don't look that nice, does anyone know how to shorten them or how we could make it more reader-friendly?

**Comment by EdgarLJH** [comment]
I think if you put square brackets around the label and the link in round brackets the link gets shorter

**Comment by hma211** [comment]
thank you, I just tried it and it works. It's been added to my current pull request with the report document
