### ISSUE TITLE
Some concerns about the additional src folder inside test folder

### ISSUE THREAD

**Issue by Lollypig** [ANU-RSES-Education/EMSC-4033-2022-assignment-Group4#22]
This problem is about the old issue we discussed in class before, which is the presence of another src folder inside the test folder. It seems like these two src folders do not automate and sync themselves, causing some troubles when I try to test the functions. So I manually sync them by copying the contents in my_function.py and paste it to the corresponding file in that additional src folder. I wonder if that causes any potential issues?

**Comment by EdgarLJH** [comment]
I just tried each one with the test_functions notebook and see which one worked. It was eventually the one in tests -> src -> functions.py. If pytest works for you it shouldn't be a problem
